# -*- coding=UTF-8 -*-
# Code generated by auto-derby-plugin-generator 801d0f5
# URL: https://natescarlet.github.io/auto-derby-plugin-generator/#/plugins/race
# Date: 2022-07-08T11:46:29.202Z

import auto_derby
from auto_derby import single_mode


from typing import Text, Dict, Tuple

_ACTION_NONE = 0
_ACTION_BAN = 1
_ACTION_LESS = 2
_ACTION_MORE = 3
_ACTION_PICK = 4

_DEFAULT_ACTION = _ACTION_NONE

_RULES: Dict[Tuple[int, Text], int] = {
    (22, "朝日杯フューチュリティステークス"): _ACTION_MORE,
    (22, "阪神ジュベナイルフィリーズ"): _ACTION_MORE,
    (23, "ホープフルステークス"): _ACTION_MORE,
    (30, "桜花賞"): _ACTION_MORE,
    (30, "皐月賞"): _ACTION_MORE,
    (32, "NHKマイルカップ"): _ACTION_MORE,
    (33, "オークス"): _ACTION_MORE,
    (33, "東京優駿（日本ダービー）"): _ACTION_MORE,
    (34, "安田記念"): _ACTION_MORE,
    (35, "宝塚記念"): _ACTION_MORE,
    (41, "スプリンターズステークス"): _ACTION_MORE,
    (43, "天皇賞（秋）"): _ACTION_MORE,
    (43, "秋華賞"): _ACTION_MORE,
    (43, "菊花賞"): _ACTION_MORE,
    (44, "エリザベス女王杯"): _ACTION_MORE,
    (45, "ジャパンカップ"): _ACTION_MORE,
    (45, "マイルチャンピオンシップ"): _ACTION_MORE,
    (53, "大阪杯"): _ACTION_PICK,
    (56, "ヴィクトリアマイル"): _ACTION_PICK,
    (58, "安田記念"): _ACTION_PICK,
    (59, "宝塚記念"): _ACTION_MORE,
}


class Plugin(auto_derby.Plugin):
    def install(self) -> None:
        class Race(auto_derby.config.single_mode_race_class):
            def score(self, ctx: single_mode.Context) -> float:
                ret = super().score(ctx)
                action = _RULES.get(
                    (ctx.turn_count(), self.name),
                    _DEFAULT_ACTION,
                )
                if action == _ACTION_BAN:
                    ret = 0
                elif action == _ACTION_LESS:
                    ret -= 5
                elif action == _ACTION_MORE:
                    ret += 5
                elif action == _ACTION_PICK:
                    ret += 100
                return ret

        auto_derby.config.single_mode_race_class = Race


auto_derby.plugin.register(__name__, Plugin())
