# -*- coding=UTF-8 -*-
# Code generated by auto-derby-plugin-generator 801d0f5
# URL: https://natescarlet.github.io/auto-derby-plugin-generator/#/plugins/race
# Date: 2022-04-06T12:26:03.693Z

import auto_derby
from auto_derby import single_mode


from typing import Text, Dict, Tuple

_ACTION_NONE = 0
_ACTION_BAN = 1
_ACTION_LESS = 2
_ACTION_MORE = 3
_ACTION_PICK = 4

_DEFAULT_ACTION = _ACTION_BAN

_RULES: Dict[Tuple[int, Text], int] = {
    (12, "ジュニア級未勝利戦"): _ACTION_PICK,
    (13, "ジュニア級未勝利戦"): _ACTION_PICK,
    (16, "札幌ジュニアステークス"): _ACTION_PICK,
    (18, "サウジアラビアロイヤルカップ"): _ACTION_PICK,
    (19, "アルテミスステークス"): _ACTION_PICK,
    (20, "デイリー杯ジュニアステークス"): _ACTION_PICK,
    (21, "京都ジュニアステークス"): _ACTION_PICK,
    (22, "阪神ジュベナイルフィリーズ"): _ACTION_PICK,
    (23, "ホープフルステークス"): _ACTION_PICK,
    (24, "京成杯"): _ACTION_PICK,
    (26, "共同通信杯"): _ACTION_PICK,
    (28, "弥生賞"): _ACTION_PICK,
    (29, "スプリングステークス"): _ACTION_PICK,
    (30, "桜花賞"): _ACTION_PICK,
    (31, "フローラステークス"): _ACTION_PICK,
    (32, "NHKマイルカップ"): _ACTION_PICK,
    (33, "オークス"): _ACTION_PICK,
    (34, "鳴尾記念"): _ACTION_PICK,
    (35, "宝塚記念"): _ACTION_PICK,
    (36, "七夕賞"): _ACTION_PICK,
    (37, "クイーンステークス"): _ACTION_PICK,
    (38, "関屋記念"): _ACTION_PICK,
    (39, "札幌記念"): _ACTION_PICK,
    (40, "ローズステークス"): _ACTION_PICK,
    (41, "セントライト記念"): _ACTION_PICK,
    (42, "京都大賞典"): _ACTION_PICK,
    (43, "秋華賞"): _ACTION_PICK,
    (44, "エリザベス女王杯"): _ACTION_PICK,
    (45, "マイルチャンピオンシップ"): _ACTION_PICK,
    (46, "中日新聞杯"): _ACTION_PICK,
    (47, "有馬記念"): _ACTION_PICK,
    (48, "日経新春杯"): _ACTION_PICK,
    (49, "アメリカJCC"): _ACTION_PICK,
    (50, "京都記念"): _ACTION_PICK,
    (51, "小倉大賞典"): _ACTION_PICK,
    (52, "中山ウマ娘ステークス"): _ACTION_PICK,
    (53, "大阪杯"): _ACTION_PICK,
    (54, "阪神ウマ娘ステークス"): _ACTION_PICK,
    (55, "天皇賞（春）"): _ACTION_PICK,
    (56, "ヴィクトリアマイル"): _ACTION_PICK,
    (57, "目黒記念"): _ACTION_PICK,
    (58, "安田記念"): _ACTION_PICK,
    (60, "函館記念"): _ACTION_PICK,
    (64, "新潟記念"): _ACTION_PICK,
    (65, "オールカマー"): _ACTION_PICK,
    (66, "府中ウマ娘ステークス"): _ACTION_PICK,
    (67, "天皇賞（秋）"): _ACTION_PICK,
    (68, "エリザベス女王杯"): _ACTION_PICK,
    (69, "ジャパンカップ"): _ACTION_PICK,
    (70, "チャレンジカップ"): _ACTION_PICK,
    (71, "有馬記念"): _ACTION_PICK,
}


class Plugin(auto_derby.Plugin):
    def install(self) -> None:
        class Race(auto_derby.config.single_mode_race_class):
            def score(self, ctx: single_mode.Context) -> float:
                ret = super().score(ctx)
                action = _RULES.get(
                    (ctx.turn_count(), self.name),
                    _DEFAULT_ACTION,
                )
                if action == _ACTION_BAN:
                    ret = 0
                elif action == _ACTION_LESS:
                    ret -= 5
                elif action == _ACTION_MORE:
                    ret += 5
                elif action == _ACTION_PICK:
                    ret += 100
                return ret

        auto_derby.config.single_mode_race_class = Race


auto_derby.plugin.register(__name__, Plugin())
