on:
  push:
    branches:
      - dev
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: dev
          version-file: version
          extra-files: |
            auto_derby/__version__.py
